version: '3.4'

services:
  bemreports:
    image: bemreports
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 d3p-dataview.py "]
    ports:
      - 5678:5678
